spring:
  cloud:
    azure:
      servicebus:
        connection-string: asasS
        enabled: true
        namespace: dear-comrade-eventhub
    function:
      definition: consume;supply;
    stream:
      bindings:
        consume-in-0:
          destination: batcave
        supply-out-0:
          destination: batcave
      poller:
        fixed-delay: 60000
        initial-delay: 0
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
          supply-out-0:
            producer:
              entity-type: queue
producer:
  name: supply-out-0