spring:
  application:
    name: dear-comrade-spring-zero-to-hero

app:
  profile: local
  level: L1-local
  emitPercent: 22-local
  noArgs: No-local
  helper:
    - "A:local"
    - "B:local"
    - "C:local"
    - "D:local"
    - "E:local"
    - "F:local"