ftpserver.user.shiva.homedirectory=C:/shiva/file-store
ftpserver.user.shiva.userpassword=shiva
ftpserver.user.shiva.enableflag=true
ftpserver.user.shiva.writepermission=true
ftpserver.user.shiva.idletime=0
ftpserver.user.shiva.maxloginnumber=0
ftpserver.user.shiva.maxloginperip=0
ftpserver.user.shiva.uploadrate=0
ftpserver.user.shiva.downloadrate=0